### Creates an user
POST http://localhost:5000/api/auth/new
Content-Type: application/json

{
    "name": "Jose",
    "email": "jose@email.com",
    "password": "123456"
}

### Login user
POST http://localhost:5000/api/auth
Content-Type: application/json

{
    "email": "jose@email.com",
    "password": "123456"
}

### Renew user token
GET http://localhost:5000/api/auth/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2Mzc3YTk4ZjQ3NTA5MzAyN2I2NmQ1ZjYiLCJuYW1lIjoiSm9zZSIsImlhdCI6MTY2ODc4NzIyMSwiZXhwIjoxNjY4Nzk0NDIxfQ.J9VFamEO5asiafnGNDbX3YLE9kTZCLt7H3m8u5MyC_Y