### Creates an user
POST {{baseUrl}}/api/auth/new
Content-Type: application/json

{
    "name": "Jose",
    "email": "jose@email.com",
    "password": "123456"
}

### Login user
POST {{baseUrl}}/api/auth
Content-Type: application/json

{
    "email": "jose@email.com",
    "password": "123456"
}

### Renew user token
GET {{baseUrl}}/api/auth/renew
x-token: {{token}}