### Get all events
GET {{baseUrl}}/api/events
x-token: {{token}}

### Create an event
POST {{baseUrl}}/api/events
Content-Type: application/json
x-token: {{token}}

{
    "title": "Girlfirend's date",
    "start": 45,
    "end": 100000,
    "notes": "Bring flowers"
}

### Update an event
PUT {{baseUrl}}/api/events/637f5f98239a75353ae02eda
Content-Type: application/json
x-token: {{token}}

{
    "title": "Another event updated!!!!!!!!!!",
    "start": 45,
    "end": 100000,
    "notes": "Whatever"
}

### Delete an event
DELETE {{baseUrl}}/api/events/45
x-token: {{token}}
