### Get all events
GET {{baseUrl}}/api/events
x-token: {{token}}

### Create an event
POST {{baseUrl}}/api/events
Content-Type: application/json
x-token: {{token}}

{
    "title": "cumpleaños del jefe",
    "start": 0,
    "end": 100000
}

### Update an event
PUT {{baseUrl}}/api/events/45
x-token: {{token}}

### Delete an event
DELETE {{baseUrl}}/api/events/45
x-token: {{token}}
